import './globals.css'
import { Inter, Rubik, Poppins } from 'next/font/google'
// made by Jose Daluz. daluzjosev@gmail.com

// Components
import Navbar from './components/Navbar'
import Footer from './components/Footer'



const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Dean Ver Tinio Portfolio',
  description: 'Generated by Jose Daluz',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        
        <Navbar/>

        {children}
        
        <Footer />

      </body>
    </html>
  )
}


