import './globals.css'
import { Inter, Rubik } from 'next/font/google'

// Components
import Navbar from './components/Navbar'




const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Dean Ver Tinio Portfolio',
  description: 'Generated by Jose Daluz',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        
        <Navbar/>
        {children}
        </body>
    </html>
  )
}


